# Generated by Django 4.1.3 on 2022-12-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetInforLowwer14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth', models.DateTimeField()),
                ('gentle', models.BooleanField(default=False)),
                ('phonenumber', models.CharField(max_length=12)),
                ('currentplace', models.CharField(max_length=300)),
                ('decaration', models.ImageField(upload_to='images/')),
                ('formed_decaration', models.ImageField(upload_to='images/')),
                ('birth_certificate', models.ImageField(upload_to='images/')),
                ('representator', models.ImageField(upload_to='images/')),
                ('cccd_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GetInforUpper14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth', models.DateTimeField()),
                ('gentle', models.BooleanField(default=False)),
                ('phonenumber', models.CharField(max_length=12)),
                ('currentplace', models.CharField(max_length=300)),
                ('declaration', models.ImageField(upload_to='images/')),
                ('oldpassport', models.ImageField(upload_to='images/')),
                ('cccd_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
