# Generated by Django 4.1.3 on 2022-12-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_currentplace_getinforlowwer14_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccd', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='GetInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth', models.DateTimeField()),
                ('gender', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=300)),
                ('guardian', models.CharField(max_length=200)),
                ('queuenumber', models.IntegerField()),
                ('cccd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to='main.cccd')),
            ],
        ),
        migrations.DeleteModel(
            name='GetInforLowwer14',
        ),
        migrations.DeleteModel(
            name='GetInforUpper14',
        ),
    ]
