# Generated by Django 4.1.3 on 2022-12-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cccd_getinfor_delete_getinforlowwer14_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinfor',
            name='birth',
            field=models.DateField(),
        ),
    ]
