# Generated by Django 4.1.3 on 2022-12-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_getinfor_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinfor',
            name='cccd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.cccd'),
        ),
    ]
